### ISSUE TITLE
Cannot read/write outside Downloads

### ISSUE THREAD

**Issue by x80486** [flathub/io.gitlab.librewolf-community#1]
Somehow, the `Firefox` Flatpak is able to do read/write outside of `Downloads`, and while I can't find the manifest for it, I can tell using `Flatseal` that they don't have `host` access — or at least I don't have.

Is there anything that can be tweaked on this manifest to make it behave in that sense like Firefox?

**Comment by lsfxz** [comment]
Judging from https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/docker/firefox-flatpak/runme.sh, the only potentially relevant difference would seem to be `--device=all` vs `--device=dri`. While the former would also allow U2F/FIDO2, it seems to be generally advised not to use it, if avoidable.

You could just try it, though – I think you can override those settings by running it with `flatpak run --device=all io.gitlab.librewolf-community`, for example. If that worked, we'd already know more :)

**Comment by x80486** [comment]
I had a good feeling that `--device=all` was not going to change anything, but still...I did it 🤣

I can't really see any obvious setting(s), except for `--filesystem=home` or `--filesystem=host`, that will accomplish that. At the same time, I don't think those should be set in the manifest by default.

I'll store-in / move-from `Downloads`then...not a big deal. Feel free to close this one...or probably leave it opened for a while, perhaps someone else have another clue.

**Comment by lsfxz** [comment]
Welp, thanks for giving it a try anyway :D

No idea what's going on there, sorry about that… I'll leave it open – maybe someone with deeper flatpak / bubblewrap / sandbox knowledges might be able to help out :)

**Comment by tommytran732** [comment]
> Judging from https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/docker/firefox-flatpak/runme.sh, the only potentially relevant difference would seem to be `--device=all` vs `--device=dri`. While the former would also allow U2F/FIDO2, it seems to be generally advised not to use it, if avoidable.
> 
> You could just try it, though – I think you can override those settings by running it with `flatpak run --device=all io.gitlab.librewolf-community`, for example. If that worked, we'd already know more :)

I was gonna open a PR for librewolf, but then I saw this comment...

`device=all` is indeed needed for U2F/FIDO2 to work. If librewolf is not configured to have it out of the box, then what is the socket=pcsc for? It is quite useless without device=all, so I think it would make more sense to either enable both or disable both.

**Comment by lsfxz** [comment]
To my (limited!) knowledge, the `pcsc` option should allow "other" smartcard usage, although it might still not even do that at the moment (eg. looking at https://github.com/valentindavid/flathub/blob/com.yubico.YubiOath/com.yubico.YubiOath.json#L34 seems to indicate that we'd might have to add pcsc-lite to the flatpak image as well).

So basically it's still in there because it's "less dangerous" than `device=all`, but it's great you've brought this up, because it seems I'd need to take a closer look at the pcsc usage anyway :)

**Comment by tommytran732** [comment]
> To my (limited!) knowledge, the `pcsc` option should allow "other" smartcard usage, although it might still not even do that at the moment (eg. looking at https://github.com/valentindavid/flathub/blob/com.yubico.YubiOath/com.yubico.YubiOath.json#L34 seems to indicate that we'd might have to add pcsc-lite to the flatpak image as well).
> 
> So basically it's still in there because it's "less dangerous" than `device=all`, but it's great you've brought this up, because it seems I'd need to take a closer look at the pcsc usage anyway :)

The YubiOath app uses the OATH interface to get the TOTP tokens stored on the Yubikey. From my understanding, `dri=pcsc` simply allows the app to talk to the pcscd socket on the host. The YubiOath app doesn't need the FIDO U2F interface at all, which is what we need for the browser. Honestly, I am not sure if adding pcsc-lite is going to solve it, but if you could make a test build for it, I will test it for ya

**Comment by x80486** [comment]
> Can you try?
> 
>     1. `about:config`
> 
>     2. `widget.use-xdg-desktop-portal` to `true`
> 
>     3. restart firefox

I think that's exactly what's missing. After that tweak it behaves the same. I believe `LibreWolf` should be released with that setting as `true` :wink:

**Comment by lsfxz** [comment]
This seems to be deprecated. `widget.use-xdg-desktop-portal.file-picker` [seems to be the correct pref](https://searchfox.org/mozilla-central/source/browser/components/BrowserGlue.jsm#4109).

I'm not yet sure if we can just set this by default, or if there are any downsides to that for non-flatpak-use.
