### ISSUE TITLE
[bug] Fonts are not anti aliased

### ISSUE THREAD

**Issue by joe733** [flathub/io.gitlab.librewolf-community#18]
![image](https://user-images.githubusercontent.com/38415384/198571567-e705d0d2-ea1e-46c5-9360-4adfa46485dd.png)

**Left:** LW | **Right:** FF

> Also how to match the host's GTK theme?

**Comment by marshallishere** [comment]
I had this issue when I was using Qt based DEs, just installed xdg-desktop-portal-gtk and it fixed.
