### ISSUE TITLE
Update runtime to 22.08

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.gitlab.librewolf-community#19]
It would be great if a latest 22.08 runtime was used if possible.

**Comment by lsfxz** [comment]
Do you know if they fixed the issues it caused a few weeks back?
(https://github.com/flathub/io.gitlab.librewolf-community/issues/12#issuecomment-1245076905)

**Comment by AsciiWolf** [comment]
Ah, I did not notice that bug. It looks like that it will be fixed when freedesktop-sdk-22.08.3 is [tagged](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tags) - that will hopefully happen in a week or two.

**Comment by AsciiWolf** [comment]
The freedesktop-sdk 22.08.3 was [released today](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tags/freedesktop-sdk-22.08.3).

**Comment by AsciiWolf** [comment]
@lsfxz #12 should be fixed in the recently released 22.08.3 freedesktop runtime.
