### ISSUE TITLE
Latest update changes settings

### ISSUE THREAD

**Issue by LegitGreenBoi** [flathub/io.gitlab.librewolf-community#25]
After updating to Librewolf 108 through Flathub it seems that my settings were changed and other odd issues occurred like getting a loading error message when opening the New Tab page.

Other users are reporting the same issues on the Librewolf subreddit.

https://www.reddit.com/r/LibreWolf/comments/znvoqh/did_the_1080_update_flatpak_didnt_apply_the/
https://www.reddit.com/r/LibreWolf/comments/zobg6c/yesterday_i_got_an_update_for_librewolf_that/

**Comment by lsfxz** [comment]
Should be fixed since quite some time (https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/flatpak-autoconf.patch)
