### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by nidamanx** [flathub/io.gitlab.librewolf-community#3]
OS: Debian GNU/Linux 10 Buster
Flatpak: 1.10.2
FireWolf: 89.0.2-1

Hi, I probably have a strange "issue". Maybe related to the User Agent setting and maybe for privacy reason.

After install:
`flatpak install io.gitlab.librewolf-community`
I decided to check browser potentials in this (and more) websites:
[https://html5test.com/](url)

All fine but, in the beginning of the page I can see:
_You are using Firefox 78.0 on Windows 10_

Any ideas to explain the reason?

Thanks and best compliments for your great project

**Comment by lsfxz** [comment]
That's actually working as intended :D

We have enabled `privacy.resistFingerprinting` by default. That setting changes (besides many other things) your User Agent to a fixed one, so everyone using that option (or Tor Browser) "looks" more or less the same with regards to fingerprinting.

**Comment by nidamanx** [comment]
Perfect. Thanks!
