### ISSUE TITLE
Downgrade completely broke my default profile

### ISSUE THREAD

**Issue by HeavenVolkoff** [flathub/io.gitlab.librewolf-community#30]
The downgrade to `v107.0.1-1` is very problematic for people that had already updated and launched `v108.0-1`. I was unable to launch LibreWolf as it only showed me an error message containing: `"Using an older version of Firefox can corrupt bookmarks and browsing history"`. The only options I had were to create a new profile or quit. This is due to Firefox's profiles not being backward compatible. As a workaround, I reinstalled v108.0-1 with the following command:
```sh
flatpak install --user https://dl.flathub.org/build-repo/124485/io.gitlab.librewolf-community.flatpakref
```

**Comment by MininuxDev** [comment]
Don't worry your profile is not "destroyed" yet, just run librewolf with the argument `--allow-downgrade`. But make a backup before, just in case
