### ISSUE TITLE
Native notifications don't work

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.gitlab.librewolf-community#7]
LibreWolf Flatpak uses legacy notifications, which on KDE Wayland looks like this (it opens in the center of the screen):

![image](https://user-images.githubusercontent.com/1454420/151797211-31cb61e0-e7eb-4105-8480-a54a1c2ce9b2.png)

In the official Firefox flatpak notifications work properly.

**Comment by Saroufim** [comment]
I second this. Is a specific permission missing?

**Comment by rsnyman** [comment]
I'm still getting this. Is there something that needs to be done to fix this?

**Comment by sentriz** [comment]
added a PR for this here https://github.com/flathub/io.gitlab.librewolf-community/pull/13
