### ISSUE TITLE
--socket=x11 should be replaced with --socket=fallback-x11

### ISSUE THREAD

**Issue by laurinneff** [flathub/io.gitlab.librewolf-community#8]
The `MOZ_ENABLE_WAYLAND` env var is set in the finish args, so why does the flatpak still have `--socket=x11` instead of `fallback-x11` where X11 access is only granted when Wayland isn't available?

**Comment by evs-ch** [comment]
That's actually a very good question – I've accidentally changed it back in 2dd62ff97473d1b8dadc69d49d99a330ce11dad1, when "syncing" some things with what Mozilla does in their Firefox flatpak conf. I'll fix it with the next release, thanks!

**Comment by lsfxz** [comment]
That's actually a very good question – I've accidentally changed it back in https://github.com/flathub/io.gitlab.librewolf-community/commit/2dd62ff97473d1b8dadc69d49d99a330ce11dad1, when "syncing" some things with what Mozilla does in their Firefox flatpak conf. I'll fix it with the next release, thanks!

**Comment by lsfxz** [comment]
Back again with a43d0613010ab0a93e2d29eff29911194d011e23!
